### PR TITLE
Used browerlist package instead of passing options to cli command directly

### LINKED ISSUE #323: "postcss" node package does not work on Windows
We should try to find an alternative or at least have a note on README first.

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #323 

@Pomax Do you mind testing on Windows? I've never developed on Windows machine before... I'm just worried it would take me a while to have the basics set up in Windows VM. 🙄

### CODE REVIEW

**Comment by Pomax** [comment]
O_O postcss no longer breaks!

**Comment by mmmavis** [comment]
YEAH 💃 🎉 🍾  :man_dancing: 

and thanks for sharing the links. Hopefully installing `node` and all other things won't be too different from what it's like on Mac 😁

**Comment by Pomax** [comment]
@gvn @mavis this looks like it's worth updating the mofo-* docs/boilerplate code with, so that future postcss use won't break npm scripts for Windows users

**Comment by mmmavis** [comment]
@gvn @Pomax remind me what those repos are. Is it just https://github.com/MozillaFoundation/mofo-style ?

**Comment by Pomax** [comment]
probably more https://github.com/MozillaFoundation/mofo-standards in the form of a section that explains that if autoprefixing is required, we use `postcss` with `browserslist` (and perhaps even explicitly say that we do *not* use `postcss` with the standard `autoprefixer` package because that doesn't work for Windows users)

**Pull request merged**
