### PR TITLE
rename "online privacy & security" to "privacy & security"

### LINKED ISSUE #736: Rename "Online Privacy & Security" to just "Privacy & Security"
It seems like "Privacy & Security" is the internet health issue name being used elsewhere (correct, @kristinashu) ? If so we should consider renaming "Online Privacy & Security" to just "Privacy & Security".

This will involve both frontend and backend work

**Back End**
- migrate all "Online Privacy & Security" bits to "Privacy & Security"
  - `/api/pulse/issues`
  - `/api/pulse/entries/?issue=Online Privacy & Security`
  - and other things I'm hoping @Pomax can lend a hand here to provide further info

**Front End**
- redirect `/issues/online-privacy-and-security` to `/issues/privacy-and-security`
- verify that all the hardcoded "Online Privacy & Security" text gets replaced.

/cc @xmatthewx @alanmoo

### PR DESCRIPTION
**Pull request by AdityaSrivast**
Fix #736 
Summary: Rename "Online privacy & security" to "Privacy & security" from route and hard-coded text

@gideonthomas @mmmavis Please review

### CODE REVIEW

**Comment by gideonthomas** [comment]
@mmmavis do you think we should be redirecting `/online-privacy-and-security` to `/privacy-and-security`?

**Comment by xmatthewx** [comment]
I took a look at analytics. While a good number of people look at this view, it is via navigation, not a landing page from incoming links. We don't need to worry about a redirect unless it is trivial.

**Comment by mmmavis** [comment]
@xmatthewx thanks for the insight.

@AdityaSrivast  code looks good to me. Nice work! 

@gideonthomas I don't wanna land this front end patch first as it can break things without the name change in backend. Please merge this PR when you have time to update the issue name on the backend.

For redirecting... To make this task simpler I'm with Matthew for not worrying about it. By default any invalid issue page url will redirect back to the issues main page `/issues` anyway.

**Comment by xmatthewx** [comment]
> By default any invalid issue page url will redirect back to the issues main page /issues anyway.

That's awesome

**Pull request merged**
