### PR TITLE
UI alignment for project cards

### PR DESCRIPTION
**Pull request by mmmavis**
Related to #720

Just some styling updates - no functionality changes.

### CODE REVIEW

**Comment by mmmavis** [comment]
@kristinashu can you give https://network-pulse-staging-pr-725.herokuapp.com/featured a quick review? If things look alright I will pass this PR to someone for code review.

**Comment by kristinashu** [comment]
Looking much better @mmmavis. I still think the titles can be closer to the heart. Example on staging, the "A" should be able to fit on the same line as "Redesign". Otherwise, everything looks good! 
screen shot 2017-10-04 at 2 47 23 pm

**Comment by mmmavis** [comment]
k PR updated!

**Comment by mmmavis** [comment]
@alanmoo yea agreed. I wanted to get this PR landed first so we can move onto other work. I will leave a note on https://github.com/mozilla/network-pulse/issues/721

**Pull request merged**
