### PR TITLE
Show character counts on fields that have character limit

### PR DESCRIPTION
**Pull request by himanish-star**
Related issue: #770
Summary: There already exists a character count for the `Title` field. Thus I have used the same thing for `Bio` and `Description` fields
GIF:
ezgif com-video-to-gif

@xmatthewx, please review.

### CODE REVIEW

**Comment by himanish-star** [comment]
@alanmoo , what do u think about this?

**Comment by alanmoo** [comment]
Looks right to me, though Mavis is more familiar with this code so I'll let her give the R+

**Comment by himanish-star** [comment]
@mmmavis , any thoughts on this

**Comment by himanish-star** [comment]
@xmatthewx , @mmmavis , Please review

**Comment by himanish-star** [comment]
@alanmoo, any updates?

**Pull request merged**
