### PR TITLE
GA changes

### PR DESCRIPTION
**Pull request by mmmavis**
Related to #746 #844 

To test locally
1. go to `js/analytics.js` and add `{debug: true}` as the 2nd parameter to line 20.
i.e., ```ReactGA.initialize(`UA-87658599-4`, {debug: true});```
2. open console on your browser dev tool
3. look for "react-ga" logs and use below as checklist

## 🔵 Clicking on any item on nav bar does NOT trigger an GA event
e.g., this should NOT happen screen shot 2017-11-20 at 5 31 30 pm

## 🔵  Profile page - clicking on social media icons and "website" link triggers an GA event
`eventLabel` should be `[name of profile owner] - type of social media icon you clicked`
e.g., screen shot 2017-11-20 at 5 40 38 pm
screen shot 2017-11-21 at 2 41 52 pm

## 🔵  Entry - clicking on project creator name triggers an GA event
`eventLabel` should be `[name of project] - [name of creator you clicked]`
e.g., screen shot 2017-11-20 at 5 36 33 pm

## 🔵  Entry - clicking on the person who submitted/published the entry triggers an GA event
`eventLabel` should be `[name of entry] -  [name of the entry submitter/publisher you clicked]`
e.g., screen shot 2017-11-20 at 5 42 23 pm

### CODE REVIEW

**Comment by mmmavis** [comment]
@xmatthewx I got a bit confused after reading through all discussion on [GitHub ticket](https://github.com/mozilla/network-pulse/issues/746) and the [spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854) as some cells don't seem up to date. Before I assign someone to review this PR, can you help verify if the PR description matches what you expect the GA events to be?

I didn't add anything related to form submission yet as there are limitations and I need more clarification on what exactly we are tracking. Let's merge this PR first and continue the form related tracking discussion in a new ticket (I'll file it).

**Comment by xmatthewx** [comment]
Your descriptions above looks great. This looks perfect. 

On profiles, do we track twitter, github, linked, _and website_? It'd be good to track outgoing website links too if that's not already included. 

Thanks!

**Comment by mmmavis** [comment]
@xmatthewx kk I'll update the spreadsheet to things are up to date there.

**Comment by xmatthewx** [comment]
For now, let's just stick with the same category and action and label it 'website' instead of twitter.

Our goal is to count and understand "productive" exits. We want to see 1) if users who exit are going from profiles to user's links, and 2) if they're strongly choosing one type of exit link over another. Using a different action makes it hard to see these side by side. If we add more flexible links later, we can evolve these labels. 

Does this make sense to you?

**Comment by mmmavis** [comment]
Cool. This is a small task so I'll update this PR to include that. Let's make sure GitHub ticket includes all todos next time so we don't introduce new task in the PR review / pending verification on staging stages! 😉

**Comment by mmmavis** [comment]
@alanmoo see PR description for testing instruction!

**Comment by mmmavis** [comment]
🎉  yay merging!

**Pull request merged**
