### PR TITLE
Added 'long bio' field to profile edit form

### PR DESCRIPTION
**Pull request by mmmavis**
Related to #920 

https://github.com/mozilla/network-pulse/pull/974/files?w=1

### CODE REVIEW

**Comment by mmmavis** [comment]
@xmatthewx 👀 ?

I had to relocate the hint message to below the field title due to technical/design restriction (there's no room below the textarea to fit it). Feel free to suggest better copy for it as I probably have grammar errors there 😂 

screen shot 2018-06-29 at 10 30 37 am
screen shot 2018-06-29 at 10 31 20 am

**Comment by mmmavis** [comment]
@xmatthewx i'll remove hint but let's keep the character count until backend increases the character limit from `4096` to a more reasonable number. Otherwise users won't be able to post if their input long bio is longer than the limit (server error).

**Comment by xmatthewx** [comment]
That copy looks good @gideonthomas. Could it be shortened a little? Either way, go for it.

**Comment by mmmavis** [comment]
🎉

**Pull request merged**
