### PR TITLE
Add contributing documentation

### PR DESCRIPTION
**Pull request by ryanwarsaw**
This PR includes a basic note about ```mofo-standards``` and adds badges for both Travis CI build status and the uses mofo-standards badge. I didn't feel the need to add this into a separate file called ```CONTRIBUTING.md``` because most of its contents were already in the README.

This may become necessary once v2 branch lands and project specific contributing information is necessary, but is outside the scope of this PR. See #139

### CODE REVIEW

**Comment by ryanwarsaw** [comment]
@mmmavis I discussed some changes in regards to this with @acabunoc but I won't be able to do anything on this for likely the next week or two (I don't have access to my development machine).

**Comment by mmmavis** [comment]
hey @ryanwarsaw no worries! there's no rush at all 😄

**Comment by alanmoo** [comment]
Heads up @ryanwarsaw, I've edited this to be against the `v1` branch, as `master` is now the react build of the site.

**Comment by Pomax** [comment]
@mavis @alanmoo @ryanwarsaw do we still want to land this?

**Comment by ryanwarsaw** [comment]
@Pomax I'm a bit lacking for time at the moment, it's something I'd like to complete once the rest of my stuff starts to land else where. I prioritized login / id work over this since it really needed it.

**Comment by Pomax** [comment]
@ryanwarsaw fair enough, just wanted to make sure this wasn't a PR that we had abandoned and was just sitting in the PR queue never to land =)

**Comment by ryanwarsaw** [comment]
I'm not going to hold up this issue any longer, if work still needs to be done by the time I finally get around to digging into this, I'll file a separate PR. In the meantime anyone is free to take the issue.

**Comment by mmmavis** [comment]
Thanks for starting this work, @ryanwarsaw ! 👍

**Pull request closed without merging**
