### PR TITLE
Staging -> Production

### PR DESCRIPTION
**Pull request by mmmavis**
Major changes
- added mofo-bootstrap
- load submitted projects on tab switch

@xmatthewx https://network-pulse.mofostaging.net/ is ready for you to review 👀

### CODE REVIEW

**Comment by mmmavis** [comment]
Oops sorry this fell through the crack. I'll update this PR today.

> Lastly, adding bootstrap adds a ton of overhead (+4897 lines). And it doesn't seem like we're leveraging it (-23 lines). Worth it? Doesn't seem like it.

@xmatthewx I would like to start utilizing our MoFo shared libraries / stack / standards so our app can be less of an outlier. If performance really becomes an issue later we will remove this dependency. 😉

**Comment by mmmavis** [comment]
@xmatthewx I updated staging with some CSS tweaks: https://network-pulse.mofostaging.net/ 👀

**Comment by xmatthewx** [comment]
Updated styles look good 👓 🔬 

If this doesn't require any code review, then I think we're good to go.

**Comment by mmmavis** [comment]
Wooohooooo 🎉

**Pull request merged**
