### PR TITLE
Add a codeowners file.

### PR DESCRIPTION
**Pull request by alanmoo**
We can adjust this as necessary, but we need something for now

### CODE REVIEW

**Comment by Pomax** [comment]
I am incredibly curious how we plan to keep this file up to date, which makes me highly apprehensive of landing a file like this.

**Comment by alanmoo** [comment]
But the alternative is that contributor PRs fall into a black hole unless someone notices them. We could make everyone get a notification (via github groups), but that seems like a bunch of unnecessary noise.

**Comment by mmmavis** [comment]
Maybe we can triage contributor PRs during our daily stands?

**Comment by alanmoo** [comment]
For projects we're actively working on, that's great. My concern is about when we're not doing that, but still have it in maintenance mode. By adding a `codeowners` file there's at least a chance that someone will see it. We could even just have it request a PR from the whole engineering team (using github groups)

**Comment by xmatthewx** [comment]
We can add more names if that's the issue. Any pathway for contacting us makes this more accessible than no pathway.

**Pull request merged**
