### PR TITLE
Added heart in fav list

### PR DESCRIPTION
**Pull request by aayushsanghavi**
#288 
patch for #70 and changes requested in #274 carried forward here

### CODE REVIEW

**Comment by mmmavis** [comment]
@aayushsanghavi I'm afraid the PR here is outdated. Please update it by rebasing the code with `master`. 😉

**Comment by aayushsanghavi** [comment]
Okay, will fix this soon and get back to you.

**Comment by mmmavis** [comment]
Hey @aayushsanghavi don't worry about it! If you have the interest to tackle it I can help review your PR otherwise don't see it as your obligation 😉 No pressure at all!

**Comment by aayushsanghavi** [comment]
Hey @mmmavis, I closed it because I couldn't get the merge conflict to work on my branch, so I deleted it and created a new one. See #315, I opened a new pull request for the same issue.

**Pull request closed without merging**
