### PR TITLE
More sign-in specificity

### PR DESCRIPTION
**Pull request by alanmoo**

### CODE REVIEW

**Comment by youriwims** [comment]
The button looks like this because it's pointing to an external link and is attempting to append an 'external link' glyph/svg that doesn't yet exist. We have a short-term fix in the new homepage PRs that'll fix this once it lands on master. Long term fix will happen in the entry page ticket/PR.
cc: @xmatthewx @alanmoo @mmmavis

**Comment by mmmavis** [comment]
image

There's supposed to be a outbound link looking glyph but I think there's a bug in the file path that's why the glyph is not showing

image

**Comment by alanmoo** [comment]
Yup; I was going to file that as a separate issue if it's not known already but I wanted to get the words fix in.

**Comment by mmmavis** [comment]
Yea let's get this merged in first!

**Comment by xmatthewx** [comment]
@jenntbeard - the login button should soon make it clear you can use either google or github.

**Comment by alanmoo** [comment]
(Probably tomorrow- the internet is having some struggles today)

**Pull request merged**
