### PR TITLE
Removed 'renderTrendingTerms' method

### PR DESCRIPTION
**Pull request by mmmavis**
Removed `renderTrendingTerms` method since it was for the old Search component and is not doing anything now on Moderation page and no longer needed.

**@gideonthomas please don't review this until you get back from PTO 😂** . Context: this cleanup work is related to PR https://github.com/mozilla/network-pulse/pull/1025.

### CODE REVIEW

**Comment by xmatthewx** [comment]
Just confirming: is this just code clean up? We'll still display trending terms, right? They don't show initially, but they appear during an active search.

**Comment by mmmavis** [comment]
@xmatthewx nope we no longer display trending terms. I removed it during the work for this ticket https://github.com/mozilla/network-pulse/issues/1013 as it didn't appear in the mockups. We can add it back to the "Search page" but that will have to be as a new ticket since this PR is to remove redundant code for displaying trending terms on the "Moderation page". We never displayed trending terms on moderation view so this dead code should be safe to remove.

**Comment by xmatthewx** [comment]
@mmmavis - I see. Sorry. I didn't realize this was just for moderation. 

Trending terms will appear on Entry search as shown here: https://github.com/mozilla/network-pulse/issues/1041. It shouldn't have been removed in #1013. That ticket was for Profile search, adding that tab and functionality. I noted in there to ignore the UI, the comp was just to demo the tab UX.

**Comment by mmmavis** [comment]
@gideonthomas Youri is working on other things on the Search page so let's add trending terms back as a separate ticket. I'll file a ticket.

**Pull request merged**
