### PR TITLE
Showed 'about' tab on profile only when there's long bio to show

### LINKED ISSUE #969: My profile shows "About" tab even if empty
STR:

1. Log in, visit https://www.mozillapulse.org/profile/me
2. Even if you don't have extended profile info enabled, you'll see the "About" link and be at that route.
(For example, https://www.mozillapulse.org/profile/93 doesn't have it, unless I'm logged in)

Expected behavior:
If extended profile info isn't enabled, you shouldn't see the tab/be on that route.

cc @xmatthewx

### PR DESCRIPTION
**Pull request by mmmavis**
Fixed #969

### CODE REVIEW

**Comment by mmmavis** [comment]
@xmatthewx can you help with design review? The review app links to staging API so you can just go on to the staging Django dashboard and make your profile changes there for QA purposes.

**Comment by alanmoo** [comment]
The code makes sense, though I don't think it can be tested currently in the review app- I'm having trouble logging in. Does Google auth need updating for a review app/staging to work or am I missing something?

**Comment by mmmavis** [comment]
@alanmoo Login doesn't seem to work directly on review apps. I think the trick (at least this is how the way I've been using) is to log in/out from **[Pulse staging via front end](https://network-pulse-staging.herokuapp.com)**.

**Comment by mmmavis** [comment]
@alanmoo R 👀 when you get a chance?

**Pull request merged**
