### PR TITLE
Making issues and tags visible on detail view

### LINKED ISSUE #523: Implement tags and issues on Detail view
Tags are awesome. The help users find related things.

 - This ticket covers adding tags to frontend of an entries detail view. 
 - Related work tracked in #500.

Note: we should present both Issues and Tags to users on entry detail view.

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #523 plus some CSS cleanup.

### CODE REVIEW

**Comment by xmatthewx** [comment]
Yay. Let me and @kristinashu know when we can take a look on staging.

**Comment by mmmavis** [comment]
Woohooo

**Comment by kristinashu** [comment]
Looks great!

**Comment by xmatthewx** [comment]
looks great. works great. ready to push to production? i think yes!

**Pull request merged**
