### PR TITLE
Adding Snyk vulnerability monitoring

### PR DESCRIPTION
**Pull request by kunal12422**
PR for Issue #717. Please review.

### CODE REVIEW

**Comment by Pomax** [comment]
Fails seem to be:
```
> network-pulse@2.0.0 test /home/travis/build/mozilla/network-pulse
> snyk test --file=package.json && run-s test:**
snyk test requires an authenticated account. Please run `snyk auth` and try again.
npm ERR! Test failed.  See above for more details.
```
@cadecairos any idea?

**Comment by cadecairos** [comment]
The encrypted token can't be used when the branch being merged isn't on the origin repo (mozilla/network-pulse)

We will need to get the branch on this repo before it will properly run...

**Comment by Pomax** [comment]
Does snyk know about "review app" keys or some other throw-away key that can be used here?

**Comment by alanmoo** [comment]
@cadecairos is this still relevant after our Snyk adjustments a week or so ago?

**Comment by alanmoo** [comment]
Sorry @kunal12422, we changed some of our configurations and this isn't needed anymore.

**Pull request closed without merging**
