### PR TITLE
Display thumbnail image if any

### LINKED ISSUE #57: Implement optional image
Users should be able to add an optional image either in the form or in the spreadsheet.

See example in comps https://redpen.io/p/by8c797c413d39c620

We might need to add some image guidelines (ex file size not too big and too small, dimensions...) or we might need to manually crop and save for web.

@mmmavis is this doable using google forms and spreadsheets?

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #57 

To QA, search for "Mozfest"... you should see a Mozilla wordmark (I used it as the thumbnail) on the card. Don't worry about styling tweaks as those will be tackled in another ticket.

screen shot 2016-08-02 at 3 14 24 pm

/cc @cadecairos @acabunoc

### CODE REVIEW

**Comment by acabunoc** [comment]
I'm gonna test out the new [quality tests](https://github.com/mozilla/network-pulse/wiki/Quality-Tests) on this! Will be checking things off as I go.

Using Firefox Developer Edition on OSX 10.9.5

### Featured view
 - [ ] this is default view for a new visitor
 - [ ] only featured cards load
 - [ ] cards are sorted by most recent at the top
 - [ ] cards display in columns to fit browser width responsively
 - [ ] cards contain title, a paragraph or two of text, two buttons, two icons

### Project card
 - [ ] Visit button opens a external link in a tab
 - [ ] Get Involved button opens a external link in a tab
 - [ ] link button reveals a URL to share (selected to copy on desktop)
 - [ ] Fav icon shows selected state when tapped

### Project shared. User opens link.
 - [ ] single project detail view displayed
 - [ ] search nav bar is showing with no menu items selected
 - [ ] no weird scrolling in the background

### Recent View
 - [ ] all cards load
 - [ ] cards are sorted with most recent at the top

### Favs View
 - [ ] shows message if no projects have been faved
 - [ ] shows all faved cards
 - [ ] fav icon shows selected state
 - [ ] clicking on the star again un-favs it and removes from this screen

### Search
 - [ ] typing triggers a live search. relevant cards hide & show. 
 - [ ] cancel search icon appears
 - [ ] search with zero results shows message

### Splash screen
 - [ ] shows briefly while app loads

### Footer
 - [ ] sign up opens google form in a tab
 - [ ] repo link opens in a tab

### 404 screen
 - [ ] shows error message for /brknURLs
 - [ ] links to repo

### Add Post Icon
 - [ ] Opens form
 - [ ] Add icon turns to Close icon
 - [ ] Form scrolls as expected
 - [ ] post is added to the spreadsheet
 - [ ] card is added to the site

### Categories/Issues screen
 - [ ] on landing users see message about issues
 - [ ] tapping on an issue only shows cards related to that issue
 - [ ] cards are sorted by most recent at the top
 - [ ] only one tag can be selected at a time

**Comment by mmmavis** [comment]
@acabunoc a lot of the things (probably 95%+) mentioned on the checklist haven't been built out yet though

**Comment by acabunoc** [comment]
yes, realizing this now

**Comment by acabunoc** [comment]
So like half of them were implemented @mmmavis! R+ on thumbnail feature :)

**Comment by mmmavis** [comment]
@acabunoc thanks! yea i'm trying to split the work into small tasks/PRs 👯

**Comment by xmatthewx** [comment]
Thanks @acabunoc – the Quality test list was written based on the new UI design. It'll become more useful after @mmmavis finishes up this week. But still awesome to have it tested on a real thing!!

**Pull request merged**
