### PR TITLE
Redirect to pulse API admin

### PR DESCRIPTION
**Pull request by cadecairos**
Related issue: https://github.com/MozillaFoundation/mofo-devops/issues/599
Summary: Adds an Express route that redirects to the Pulse API admin.

### CODE REVIEW

**Comment by patjouk** [comment]
I was mentioning those pages when you get redirect out of a domain to go to another one: "You're leaving X website, clear here to continue."

It's just that if you use the prod API as backend for local dev, you might do something bad by accident. The default is set up to pulse staging, but you never know.

**Comment by cadecairos** [comment]
I'm not entirely sold on the need for an entire page and client-side redirect. But how about we only add the route if `NODE_ENV === 'production`

**Comment by patjouk** [comment]
Yeah, that's a better and faster solution.

**Comment by cadecairos** [comment]
@patjouk updated and ready for re-review

**Pull request merged**
